// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYamh3HP1gQl8EObLRcl9p5mx7-O4R4Tw',
    appId: '1:990041771396:web:8bd6f54c0c56c3acc561d1',
    messagingSenderId: '990041771396',
    projectId: 'gdsc-krin-sranan',
    authDomain: 'gdsc-krin-sranan.firebaseapp.com',
    storageBucket: 'gdsc-krin-sranan.appspot.com',
    measurementId: 'G-QHSVFSQKVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx5Wm03btIAjzQVHOz6t8z7ULJ2pWR83E',
    appId: '1:990041771396:android:f397250ec5cb00bcc561d1',
    messagingSenderId: '990041771396',
    projectId: 'gdsc-krin-sranan',
    storageBucket: 'gdsc-krin-sranan.appspot.com',
  );
}
